[tool.poetry]
name = "openbb-core"
version = "0.2.0"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_core" }]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.20.0"
importlib_metadata = "^6.8.0"
websockets = "^10.4"
pandas = ">1.5.3"
requests = "^2.28.2"
html5lib = "^1.1"
fastapi = "^0.100.1"
passlib = "^1.7.4"
python-jose = "^3.3.0"
uuid7 = "^0.1.0"
posthog = "^3.0.1"
python-multipart = "^0.0.6"
bcrypt = "^4.0.1"
urllib3 = "<2.0.0"
openbb-provider = { path = "../provider" }

[tool.poetry.group.dev.dependencies]
openbb-provider = { path = "../provider" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
