[tool.poetry]
name = "openbb-charting"
version = "0.1.0"
description = "Charting extension for OpenBB SDK"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_charting" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"  # scipy forces python <4.0 explicitly
openbb-core = { path = "../../sdk/core" }
scipy = "^1.10.0"
plotly = "^5.15.0"
statsmodels = "^0.14.0"
reportlab = "^4.0.4"
pywry = "^0.5.13"
svglib = "^1.5.1"
aiohttp = "^3.8.4"
nbformat = "^5.9.0"
pandas = ">1.5.3"
pandas-ta = "^0.3.14b0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
openbb_charting = "openbb_charting.charting_router:router"
